[project]
name = "yolocli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytubefix>=10.3.6",
    "ultralytics>=8.4.11",
    "x-anylabeling-cvhub>=3.3.9",
]
